import 'package:flutter/material.dart';

var type = 0;
var year = 1;
var firstName = TextEditingController();
var middleName = TextEditingController();
var lastName = TextEditingController();
var rollNumber = TextEditingController();
var personalMobile = TextEditingController();
var addressLine1 = TextEditingController();
var addressLine2 = TextEditingController();
var city = TextEditingController();
var state = TextEditingController();
var motherOccupation = TextEditingController();
var motherName = TextEditingController();
var fatherOccupation = TextEditingController();
var fatherName = TextEditingController();
var fatherMobile = TextEditingController();
var motherMobile = TextEditingController();
var aadhaar = TextEditingController();
var edit = true;
var accountNumber = TextEditingController();
var accountName = TextEditingController();
var bankIFSC = TextEditingController();
var selectedIncome;
var incomeOptions = ['less than Rs10,000','Rs10,000-Rs20,000'];
var selectedYear;
var yearOptions = ['1st','2nd'];
var cg = TextEditingController();
var backlog = TextEditingController();
var jee = TextEditingController();
var boards = TextEditingController();
var specialOptions = ['Yes','No'];
var selectedCase;
var specialText = TextEditingController();